/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StackIndexImport } from './routes/stack.index'
import { Route as StackStackImport } from './routes/stack.$stack'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const StackIndexRoute = StackIndexImport.update({
  id: '/stack/',
  path: '/stack/',
  getParentRoute: () => rootRoute,
} as any)

const StackStackRoute = StackStackImport.update({
  id: '/stack/$stack',
  path: '/stack/$stack',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/stack/$stack': {
      id: '/stack/$stack'
      path: '/stack/$stack'
      fullPath: '/stack/$stack'
      preLoaderRoute: typeof StackStackImport
      parentRoute: typeof rootRoute
    }
    '/stack/': {
      id: '/stack/'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/stack/$stack': typeof StackStackRoute
  '/stack': typeof StackIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/stack/$stack': typeof StackStackRoute
  '/stack': typeof StackIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/stack/$stack': typeof StackStackRoute
  '/stack/': typeof StackIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/stack/$stack' | '/stack'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/stack/$stack' | '/stack'
  id: '__root__' | '/' | '/about' | '/stack/$stack' | '/stack/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  StackStackRoute: typeof StackStackRoute
  StackIndexRoute: typeof StackIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  StackStackRoute: StackStackRoute,
  StackIndexRoute: StackIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/stack/$stack",
        "/stack/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/stack/$stack": {
      "filePath": "stack.$stack.tsx"
    },
    "/stack/": {
      "filePath": "stack.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
