class KptnError(Exception): ...
class GraphError(KptnError): ...
class ProfileError(KptnError): ...
class TaskError(KptnError): ...
class StateStoreError(KptnError): ...
class HashError(KptnError): ...
